name: monedo
description: App de finanzas personales - Monedo
publish_to: 'none'
version: 2.2.1+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  # Gráficas
  fl_chart: ^0.68.0
  # Almacenamiento local
  shared_preferences: ^2.0.0
  # Encriptación
  crypto: ^3.0.3
  # Iconos
  cupertino_icons: ^1.0.2
  excel: ^4.0.6
  pdf: ^3.11.1
  share_plus: ^10.1.2
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"