// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZp1zl_eUGa6JsPIYXHi8ku7e9oIryA30',
    appId: '1:1059318428832:web:48805c718b2202ac4805c5',
    messagingSenderId: '1059318428832',
    projectId: 'monedo-e7849',
    authDomain: 'monedo-e7849.firebaseapp.com',
    storageBucket: 'monedo-e7849.firebasestorage.app',
    measurementId: 'G-DZWFDF8DJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARREEdznH0bkGfNU2O6kVy7FkMRfngbng',
    appId: '1:1059318428832:android:5d47be3dc6877c644805c5',
    messagingSenderId: '1059318428832',
    projectId: 'monedo-e7849',
    storageBucket: 'monedo-e7849.firebasestorage.app',
  );
}
