import 'package:flutter/material.dart';

/// Íconos de las categorías predeterminadas de la app.
const Map<String, IconData> kDefaultCategoryIcons = {
  'Alimentación': Icons.restaurant_rounded,
  'Transporte': Icons.directions_car_rounded,
  'Entretenimiento': Icons.movie_rounded,
  'Salud': Icons.health_and_safety_rounded,
  'Educación': Icons.school_rounded,
  'Ropa': Icons.checkroom_rounded,
  'Hogar': Icons.home_rounded,
  'Trabajo': Icons.work_rounded,
  'Inversión': Icons.trending_up_rounded,
  'Ahorro': Icons.savings_rounded,
  'Ocio': Icons.celebration_rounded,
  'Otros': Icons.attach_money_rounded,
  'Transferencia': Icons.swap_horiz_rounded,
};

/// Librería extensa de íconos para elegir al crear una categoría propia,
/// con una etiqueta legible para poder buscarlos.
const List<MapEntry<String, IconData>> kCategoryIconChoices = [
  MapEntry('Restaurante', Icons.restaurant_rounded),
  MapEntry('Comida rápida', Icons.fastfood_rounded),
  MapEntry('Café', Icons.local_cafe_rounded),
  MapEntry('Bar', Icons.local_bar_rounded),
  MapEntry('Supermercado', Icons.local_grocery_store_rounded),
  MapEntry('Compras', Icons.shopping_bag_rounded),
  MapEntry('Carrito', Icons.shopping_cart_rounded),
  MapEntry('Panadería', Icons.bakery_dining_rounded),
  MapEntry('Transporte', Icons.directions_car_rounded),
  MapEntry('Taxi', Icons.local_taxi_rounded),
  MapEntry('Bus', Icons.directions_bus_rounded),
  MapEntry('Tren', Icons.train_rounded),
  MapEntry('Metro', Icons.subway_rounded),
  MapEntry('Bicicleta', Icons.pedal_bike_rounded),
  MapEntry('Combustible', Icons.local_gas_station_rounded),
  MapEntry('Estacionamiento', Icons.local_parking_rounded),
  MapEntry('Mecánico', Icons.car_repair_rounded),
  MapEntry('Avión', Icons.flight_rounded),
  MapEntry('Hotel', Icons.hotel_rounded),
  MapEntry('Equipaje', Icons.luggage_rounded),
  MapEntry('Playa', Icons.beach_access_rounded),
  MapEntry('Mapa', Icons.map_rounded),
  MapEntry('Entretenimiento', Icons.theater_comedy_rounded),
  MapEntry('Cine', Icons.movie_rounded),
  MapEntry('Música', Icons.music_note_rounded),
  MapEntry('Videojuegos', Icons.sports_esports_rounded),
  MapEntry('Streaming', Icons.subscriptions_rounded),
  MapEntry('Suscripciones', Icons.autorenew_rounded),
  MapEntry('Televisión', Icons.tv_rounded),
  MapEntry('Libros', Icons.menu_book_rounded),
  MapEntry('Fiesta', Icons.celebration_rounded),
  MapEntry('Regalos', Icons.card_giftcard_rounded),
  MapEntry('Salud', Icons.health_and_safety_rounded),
  MapEntry('Hospital', Icons.local_hospital_rounded),
  MapEntry('Medicinas', Icons.medication_rounded),
  MapEntry('Doctor', Icons.medical_services_rounded),
  MapEntry('Dentista', Icons.healing_rounded),
  MapEntry('Gimnasio', Icons.fitness_center_rounded),
  MapEntry('Deportes', Icons.sports_soccer_rounded),
  MapEntry('Ciclismo', Icons.directions_bike_rounded),
  MapEntry('Natación', Icons.pool_rounded),
  MapEntry('Yoga', Icons.self_improvement_rounded),
  MapEntry('Educación', Icons.school_rounded),
  MapEntry('Cursos', Icons.laptop_mac_rounded),
  MapEntry('Universidad', Icons.account_balance_rounded),
  MapEntry('Hogar', Icons.home_rounded),
  MapEntry('Renta', Icons.apartment_rounded),
  MapEntry('Electricidad', Icons.bolt_rounded),
  MapEntry('Agua', Icons.water_drop_rounded),
  MapEntry('Gas', Icons.local_fire_department_rounded),
  MapEntry('Internet', Icons.wifi_rounded),
  MapEntry('Teléfono', Icons.phone_iphone_rounded),
  MapEntry('Muebles', Icons.chair_rounded),
  MapEntry('Limpieza', Icons.cleaning_services_rounded),
  MapEntry('Herramientas', Icons.build_rounded),
  MapEntry('Jardín', Icons.yard_rounded),
  MapEntry('Mascotas', Icons.pets_rounded),
  MapEntry('Bebé', Icons.child_friendly_rounded),
  MapEntry('Niños', Icons.child_care_rounded),
  MapEntry('Ropa', Icons.checkroom_rounded),
  MapEntry('Zapatos', Icons.hiking_rounded),
  MapEntry('Belleza', Icons.face_retouching_natural_rounded),
  MapEntry('Peluquería', Icons.content_cut_rounded),
  MapEntry('Spa', Icons.spa_rounded),
  MapEntry('Caridad', Icons.volunteer_activism_rounded),
  MapEntry('Seguros', Icons.security_rounded),
  MapEntry('Impuestos', Icons.receipt_long_rounded),
  MapEntry('Legal', Icons.gavel_rounded),
  MapEntry('Trabajo', Icons.work_rounded),
  MapEntry('Oficina', Icons.business_center_rounded),
  MapEntry('Reuniones', Icons.groups_rounded),
  MapEntry('Inversión', Icons.trending_up_rounded),
  MapEntry('Ahorro', Icons.savings_rounded),
  MapEntry('Banco', Icons.account_balance_rounded),
  MapEntry('Tarjeta', Icons.credit_card_rounded),
  MapEntry('Efectivo', Icons.payments_rounded),
  MapEntry('Criptomonedas', Icons.currency_bitcoin_rounded),
  MapEntry('Tecnología', Icons.devices_rounded),
  MapEntry('Computador', Icons.computer_rounded),
  MapEntry('Celular', Icons.smartphone_rounded),
  MapEntry('Cámara', Icons.camera_alt_rounded),
  MapEntry('Auriculares', Icons.headphones_rounded),
  MapEntry('Nube', Icons.cloud_rounded),
  MapEntry('Arte', Icons.palette_rounded),
  MapEntry('Fotografía', Icons.photo_camera_rounded),
  MapEntry('Reciclaje', Icons.recycling_rounded),
  MapEntry('Naturaleza', Icons.park_rounded),
  MapEntry('Montaña', Icons.terrain_rounded),
  MapEntry('Iglesia', Icons.church_rounded),
  MapEntry('Bandera', Icons.flag_rounded),
  MapEntry('Favorito', Icons.star_rounded),
  MapEntry('Corazón', Icons.favorite_rounded),
  MapEntry('Etiqueta', Icons.label_rounded),
  MapEntry('Otros', Icons.category_rounded),
];

/// Registro reactivo (icono por categoría) para que cualquier pantalla
/// muestre el icono correcto de categorías propias sin recargar todo.
class CategoryIconRegistry {
  static final ValueNotifier<Map<String, IconData>> customIcons =
      ValueNotifier<Map<String, IconData>>({});

  static IconData iconFor(String category) {
    return customIcons.value[category] ??
        kDefaultCategoryIcons[category] ??
        Icons.category_rounded;
  }
}
